spring:
  profiles:
    active: dev
  application:
    name: mijing

#  mybatis:
#   # dao-locations: classpath*:C:com\mijing\dao\*.xml
#    mapperLocations: classpath:/mapper/*.xml
##       type-aliases-package: com.alibaba.fastjson.JSONObject

